# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        arguments: -t student-api:latest
        tags: |
          $(tag)
    - task: ECRPushImage@1
      inputs:
        awsCredentials: 'ecr-push'
        regionName: 'ap-southeast-1'
        imageSource: 'imagename'
        sourceImageName: 'student-api'
        repositoryName: 'student-api'
        autoCreateRepository: true
        outputVariable: 'student-api-image'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'echo "$(Build.BuildNumber)" > $(Build.ArtifactStagingDirectory)/build.txt'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
